### ISSUE TITLE
How to use custom dataset 

### ISSUE THREAD

**Issue by Kyangzhou** [JCLArriaga5/MOT15-Detectron2-Sort-DeepSort#1]
I have already  use custom dataset to detect my objects in Detectron2 and wan use  DeepSort to track them. So how can I  achieve  it ? Thank you!

**Comment by JCLArriaga5** [comment]
Hello, sorry to answer so far 🙏

First you must generate the `det.npy` file of detections of the dataset that you want to use for [Deep SORT](https://github.com/nwojke/deep_sort)

Detections must be saved in the following format:
```html
<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>
```

In the [colab](https://colab.research.google.com/drive/1hhtoMwFxpOGXiXtIjEBeST9rQ6BdF5Gm?usp=sharing) file of my repository you can find how I did to [generate the file](https://colab.research.google.com/drive/1hhtoMwFxpOGXiXtIjEBeST9rQ6BdF5Gm#scrollTo=zdezCC_0VqYp&line=1&uniqifier=1), I hope it will be of help to you.
